### ISSUE TITLE
请问如何将数据库换成自己的？如何在服务器上运行？

### ISSUE THREAD

**Issue by Cheese-Yu** [linguowei/myblog#2]
小白，请博主指教，谢谢~

**Comment by linguowei** [comment]
把server文件夹里面db.js 的mongoose.connect地址改成你自己的数据库地址就好了，如何在服务器上运行这个问题问的太泛了，你可搜搜如何在服务器上部署node,有很多资料可以自己去看看

**Comment by Cheese-Yu** [comment]
好的，十分感谢

**Comment by leeseean** [comment]
events.js:163
      throw er; // Unhandled 'error' event
      ^
MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (D:\projects\myblog\node_modules\mongodb-core\lib\topologies\server.js:328:35)
    at emitOne (events.js:96:13)
    at Pool.emit (events.js:191:7)
    at Connection.<anonymous> (D:\projects\myblog\node_modules\mongodb-core\lib\connection\pool.js:274:12)
    at Object.onceWrapper (events.js:293:19)
    at emitTwo (events.js:106:13)
    at Connection.emit (events.js:194:7)
    at Socket.<anonymous> (D:\projects\myblog\node_modules\mongodb-core\lib\connection\connection.js:177:49)
    at Object.onceWrapper (events.js:293:19)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at emitErrorNT (net.js:1283:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)克隆下来报错怎么回事？

**Comment by leeseean** [comment]
mongoose.connect('mongodb://127.0.0.1:27017/')这个地址怎么写，怎么知道我自己的数据库地址在哪里？

**Comment by linguowei** [comment]
@leeseean **mongodb://127.0.0.1:27017** 这个地址指的是你本机的**mongodb**数据库的地址，27017端口是**mongodb**的默认端口，首先你要在你本机电脑安装**mongodb**,然后启动**mongodb**的服务才能连接
